# Hands On

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\Frags\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

# Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,5,6,12])
a

array([ 1,  2,  3,  5,  6, 12])

In [7]:
a[2]

3

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  5,  6, 12])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimenational arrays

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [19]:
n[0]

array([1, 2, 3])

In [20]:
n[0][1]

2

In [21]:
n[0][1] = 20

In [22]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[:,2] # getting the third column

array([3, 6, 9])

# Randomly generated arrays

In [26]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [28]:
np.random.seed(10)
np.random.randn(5,2) # random from normal distributions

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [29]:
np.random.seed(10)
np.random.randint(low=0, high=100, size=(5,2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

# Element-wise operations

In [30]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
a + 1

array([1, 2, 3, 4, 5])

In [32]:
a * 2

array([0, 2, 4, 6, 8])

In [33]:
(10 + (a*2)) ** 2

array([100, 144, 196, 256, 324], dtype=int32)

In [34]:
b = (10 + (a*2)) ** 2

In [36]:
a+b+10

array([110, 155, 208, 269, 338])

# Comparison operations

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a >= 2

array([False, False,  True,  True,  True])

In [40]:
b

array([100, 144, 196, 256, 324], dtype=int32)

In [39]:
a > b

array([False, False, False, False, False])

In [42]:
a[a<b]

array([0, 1, 2, 3, 4])

# Summarizing operations

In [44]:
a

array([0, 1, 2, 3, 4])

In [43]:
a.min()

0

In [45]:
a.sum()

10

In [46]:
a.mean()

2.0

In [47]:
a.std()

1.4142135623730951

In [48]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [49]:
n.sum()

63

In [50]:
n.min()

1

In [51]:
n.std()

5.163977794943222